version: "3.9"

services:

  node-server:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
    container_name: node-server
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - .env
    # restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
